server:
  port: 8080
  servlet:
    context-path: "/spring-shiro"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/idea_test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name:

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
